import supabase from '../../backend/supabaseSetup.js'

export default async function createAccount({ email, password, name})
{

    //uses supabase's built-in table for creating users: each user in this table has their email, password, and unique id
    const { data: userData, error: authError } = await supabase.auth.admin.createUser({
        email,
        password,
        email_confirm: true
    })

    if (authError) {
        throw new Error(authError?.message || 'Invalid email or password');     
    }
//takes the unique id generated by supabases's auth
    const userID = userData.user.id
//inserts unique id, email, and display name into our custom "users" table
    const { error: dbError } = await supabase.from('users').insert({
        user_id: userID,
        user_email: email,
        user_name: name

    })

    if (dbError) {
        throw new Error(dbError?.message || 'database insertion error');
    }

    return {success:true, user: userData.user}


}
