import supabase from '../../backend/supabaseSetup.js'

export default async function createAccount({ email, password, display_name})
{

    //uses supabase's built-in table for creating users: each user in this table has their email, password, and unique id
    const { data: userData, error: authError } = await supabase.auth.admin.createUser({
        email,
        password,
        email_confirm: true
    })

    if (authError) {
        console.error('Auth creation error: ', authError)
        return {success: false, error: authError.message}
    }
//takes the unique id generated by supabases's auth
    const userID = userData.user.id
//inserts unique id, email, and display name into our custom "users" table
    const { error: dbError } = await supabase.from('users').insert({
        user_id: userID,
        user_email: email,
        user_name: display_name

    })

    if (dbError) {
        console.error('Database insert error: ', dbError)
        return {success: false, error: dbError.message }
    }

    return {success:true, user: userData.user}


}
